# Site settings
title: Rosillo Labs
email: DanielRosillo@protonmail.com
description: Rosillo Labs is a software development studio.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://rosillolabs.com" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-143262290-1"
addthis_id: ra-5d9242279fb8ace7
disqus_account: highbox

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/danielrosillo22
  - title: facebook
    url: https://www.facebook.com/HighboxApp
  - title: github
    url: https://github.com/DanielRosillo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed,jekyll-sitemap,jekyll-seo-tag]
# Build settings

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

  # SEO/OpenGraph
logo: /img/logo.png

twitter:
  username: danielrosillo22
  card: summary

social:
  name: CloudSh
  links:
    - https://twitter.com/danielrosillo22
    - https://github.com/danielrosillo

author:
  twitter: danielrosillo22

defaults:
  - scope:
      path: ""
    values:
      image: /img/logo.png
      author: Daniel Rosillo
# /SEO
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

  
