# Site settings
title: Rosillo Labs
email: DanielRosillo@protonmail.com
description: Rosillo Labs is a software studio.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://DanielRosillo.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-143262290-1"
addthis_id: ra-5644da281510c62f
disqus_account: highbox

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/danielrosillo22
  - title: facebook
    url: https://www.facebook.com/HighboxApp
  - title: github
    url: https://github.com/DanielRosillo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed,jekyll-sitemap,jekyll-seo-tag]
# Build settings

plugins:

  - jekyll-sitemap
  - jekyll-seo-tag
